/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package proyectopoo2025;

import Controller.GestionConsulta;
import Model.Orden;

import Model.GestionOrden;
import javax.swing.JOptionPane;

public class DatosOrden extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(DatosOrden.class.getName());

    /**
     * Creates new form DatosOrden
     */
    private GestionOrden gestor;
    private int indiceModificar = -1;
    private DatosConsulta ventanaConsulta;

    
    public DatosOrden(GestionOrden gestor, DatosConsulta ventanaConsulta) {
        this.gestor = gestor;
        this.ventanaConsulta = ventanaConsulta;
        initComponents();
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        tfProcedimiento = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jbTipo = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        tfPrecio = new javax.swing.JTextField();
        jbEstado = new javax.swing.JComboBox<>();
        bAceptar = new javax.swing.JButton();
        bCancelar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Descripcion:");

        tfProcedimiento.setText("jTextField1");
        tfProcedimiento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfProcedimientoActionPerformed(evt);
            }
        });

        jLabel2.setText("Tipo de Orden:");

        jbTipo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Laboratorio", "Imagen", "Procedimiento" }));
        jbTipo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbTipoActionPerformed(evt);
            }
        });

        jLabel3.setText("Estado");

        jLabel4.setText("Precio (S/.):");

        tfPrecio.setText("jTextField1");

        jbEstado.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Pendiente", "En Proceso", "Con Resultado", "Entregado" }));

        bAceptar.setText("Aceptar");
        bAceptar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bAceptarActionPerformed(evt);
            }
        });

        bCancelar.setText("Cancelar");
        bCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bCancelarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel1))
                            .addComponent(jLabel4))
                        .addGap(97, 97, 97)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jbTipo, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(tfProcedimiento)
                            .addComponent(tfPrecio)
                            .addComponent(jbEstado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(54, 54, 54)
                        .addComponent(bAceptar)
                        .addGap(84, 84, 84)
                        .addComponent(bCancelar)))
                .addContainerGap(88, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(45, 45, 45)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(jbTipo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(tfProcedimiento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 22, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4)
                    .addComponent(tfPrecio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(jLabel3))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jbEstado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bAceptar)
                    .addComponent(bCancelar))
                .addGap(28, 28, 28))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

        public void setDatos(Orden o, int indice) {
         this.indiceModificar = indice;
         jbTipo.setSelectedItem(o.getNombre());
         tfProcedimiento.setText(o.getDescripcion());
         jbEstado.setSelectedItem(o.getEstado());
         tfPrecio.setText(String.valueOf(o.getPrecio()));
     }
    
    private void tfProcedimientoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfProcedimientoActionPerformed
                // TODO add your handling code here:
            
        
    }//GEN-LAST:event_tfProcedimientoActionPerformed

    private void bAceptarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bAceptarActionPerformed
    
    String tipo = jbTipo.getSelectedItem().toString();
    String procedimiento = tfProcedimiento.getText();
    String precioTxt = tfPrecio.getText();
    String estado = jbEstado.getSelectedItem().toString();

    if (procedimiento.isEmpty() || precioTxt.isEmpty()) {
        JOptionPane.showMessageDialog(null, "Complete todos los campos obligatorios");
        return;
    }
    double precio;
    precio = Double.parseDouble(precioTxt);

    if (indiceModificar == -1) {

        Orden nueva = new Orden(tipo, procedimiento, precio, estado);

        
        gestor.agregarOrden(nueva);

        JOptionPane.showMessageDialog(null, "Orden registrada correctamente");

    } else {

        gestor.modificarOrden(indiceModificar, tipo, procedimiento, precio, estado);
        JOptionPane.showMessageDialog(null, "Orden modificada correctamente");
    }


    jbTipo.setSelectedIndex(0);
    tfProcedimiento.setText("");
    tfPrecio.setText("");
    jbEstado.setSelectedIndex(0);


    GestorOrden tabla = new GestorOrden(ventanaConsulta);
    tabla.setVisible(true);
    this.dispose();
    }//GEN-LAST:event_bAceptarActionPerformed

    private void jbTipoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbTipoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jbTipoActionPerformed

    private void bCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bCancelarActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_bCancelarActionPerformed

    /**
     * @param args the command line arguments
     */


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bAceptar;
    private javax.swing.JButton bCancelar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JComboBox<String> jbEstado;
    private javax.swing.JComboBox<String> jbTipo;
    private javax.swing.JTextField tfPrecio;
    private javax.swing.JTextField tfProcedimiento;
    // End of variables declaration//GEN-END:variables
}
