/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package proyectopoo2025;

import Controller.GestionCitas;
import Controller.GestionEmpleados;
import Controller.GestionPaciente;
import Model.Cita;
import Model.Empleado;
import Model.Medico;
import Model.Paciente;
import javax.swing.JOptionPane;

/**
 *
 * @author Usuario
 */
public class DatosCitas extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(DatosCitas.class.getName());

    /**
     * Creates new form DatosCitas
     */
    
    private GestionCitas gestorCitas;
    private GestionPaciente gestorPacientes;
    private GestionEmpleados gestorEmpleados;
    private int indiceModificar = -1;
    
    public DatosCitas(GestionCitas gestor, GestionPaciente gestorPacientes, GestionEmpleados gestorEmpleados) {
    this.gestorCitas = gestor;
    this.gestorPacientes = gestorPacientes;
    this.gestorEmpleados = gestorEmpleados;

    initComponents();

    cargarPacientes();
    cargarMedicos();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        tfCodigodeConsultorio = new javax.swing.JTextField();
        jbModalidad = new javax.swing.JComboBox<>();
        jbPaciente = new javax.swing.JComboBox<>();
        jbMedico = new javax.swing.JComboBox<>();
        jbFecha = new javax.swing.JComboBox<>();
        jLabel6 = new javax.swing.JLabel();
        jbHora = new javax.swing.JComboBox<>();
        jbAgregar = new javax.swing.JButton();
        jbCancelar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Código del Consultorio");

        jLabel2.setText("Modalidad");

        jLabel3.setText("Paciente");

        jLabel4.setText("Médico");

        jLabel5.setText("Fecha");

        tfCodigodeConsultorio.setText("jTextField1");

        jbModalidad.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Presencial", "Virtual" }));

        jbPaciente.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jbPaciente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbPacienteActionPerformed(evt);
            }
        });

        jbMedico.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jbMedico.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbMedicoActionPerformed(evt);
            }
        });

        jbFecha.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "2025-12-01 ", "2025-12-02 ", "2025-12-03", "2025-12-04 " }));

        jLabel6.setText("Hora");

        jbHora.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "9:00", "10:00", "11:00", "12:00", "13:00", "14:00", "15:00", "16:00", "17:00", "18:00", "19:00", "20:00" }));

        jbAgregar.setText("Agregar");
        jbAgregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbAgregarActionPerformed(evt);
            }
        });

        jbCancelar.setText("Cancelar");
        jbCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbCancelarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel6)
                    .addComponent(jLabel5)
                    .addComponent(jLabel4)
                    .addComponent(jLabel3)
                    .addComponent(jLabel2)
                    .addComponent(jLabel1)
                    .addComponent(jbAgregar))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 73, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jbCancelar)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(tfCodigodeConsultorio, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jbModalidad, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jbPaciente, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jbMedico, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jbFecha, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jbHora, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(24, 24, 24))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(72, 72, 72)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(tfCodigodeConsultorio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(15, 15, 15)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel2)
                    .addComponent(jbModalidad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(25, 25, 25)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jbPaciente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(19, 19, 19)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jbMedico, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(15, 15, 15)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jbFecha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(jbHora, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jbAgregar)
                    .addComponent(jbCancelar))
                .addContainerGap(36, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public void cargarPacientes() {
        jbPaciente.removeAllItems();

        for (int i = 0; i < gestorPacientes.getNumPacientes(); i++) {
            Paciente p = gestorPacientes.getPaciente(i);
            jbPaciente.addItem(p.getApellido());
        }
    }
    
    public void setDatos(Cita c, int indice) {
        
        this.indiceModificar = indice;

        jbFecha.setSelectedItem(c.getFecha());
        jbHora.setSelectedItem(c.getHora());
        jbPaciente.setSelectedItem(c.getPaciente().getApellido());
        jbMedico.setSelectedItem(c.getMedico().getApellidos());
        jbModalidad.setSelectedItem(c.getModalidad());
        tfCodigodeConsultorio.setText(c.getCodigoConsultorio());
    }
    
    public void cargarMedicos() {
    jbMedico.removeAllItems();

    for (int i = 0; i < gestorEmpleados.getNroEmpleados(); i++) {
        Empleado e = gestorEmpleados.getEmpleados(i);

        if (e.getRol().toLowerCase().contains("med")) {
            jbMedico.addItem(e.getApellidos());
            }
        }
    }
    
    private void jbPacienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbPacienteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jbPacienteActionPerformed

    private void jbMedicoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbMedicoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jbMedicoActionPerformed

    private void jbAgregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbAgregarActionPerformed
        
        String modalidad = jbModalidad.getSelectedItem().toString();
        String fecha = jbFecha.getSelectedItem().toString();
        String hora = jbHora.getSelectedItem().toString();
        String codigoConsultorio = tfCodigodeConsultorio.getText();

            if (modalidad.isEmpty() ||
        fecha.isEmpty() || hora.isEmpty() || codigoConsultorio.isEmpty()) {

        JOptionPane.showMessageDialog(this, 
                "Complete todos los campos obligatorios");
        return;
    }

        String textoPaciente = jbPaciente.getSelectedItem().toString();

        
        Paciente pac = null;
        for (int i = 0; i < gestorPacientes.getNumPacientes(); i++) {
            Paciente p = gestorPacientes.getPaciente(i);
            
            if (textoPaciente.equalsIgnoreCase(p.getApellido())) {
                pac = p;
                break;
            }
        }

        if (pac == null) {
            JOptionPane.showMessageDialog(this, "No se encontró el paciente seleccionado");
            return;
        }

    
        String textoMedico = jbMedico.getSelectedItem().toString();

        Medico med = null;

        for (int i = 0; i < gestorEmpleados.getNroEmpleados(); i++) {
            Empleado e = gestorEmpleados.getEmpleados(i);

            if (e.getRol().equalsIgnoreCase("Medico") &&
                e.getApellidos().equalsIgnoreCase(textoMedico)) {

                med = new Medico(
                    e.getDNI(),
                    e.getNombres(),
                    e.getApellidos(),
                    e.getRol(),
                    e.getEspecialidad(),
                    e.getTelefono(),
                    e.getCorreo()
        );
            }
        }

        if (med == null) {
            JOptionPane.showMessageDialog(this, "No se encontró el médico seleccionado");
            return;
        }

        Cita c = new Cita(codigoConsultorio, fecha, hora, modalidad, pac, med);
        gestorCitas.agregarCita(c);

        JOptionPane.showMessageDialog(this, "Cita registrada correctamente");

        this.dispose();
}//GEN-LAST:event_jbAgregarActionPerformed

    private void jbCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbCancelarActionPerformed
        this.dispose();
    }//GEN-LAST:event_jbCancelarActionPerformed

    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JButton jbAgregar;
    private javax.swing.JButton jbCancelar;
    private javax.swing.JComboBox<String> jbFecha;
    private javax.swing.JComboBox<String> jbHora;
    private javax.swing.JComboBox<String> jbMedico;
    private javax.swing.JComboBox<String> jbModalidad;
    private javax.swing.JComboBox<String> jbPaciente;
    private javax.swing.JTextField tfCodigodeConsultorio;
    // End of variables declaration//GEN-END:variables
}
