/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package proyectopoo2025;

/**
 *
 * @author Usuario
 */

    import Controller.GestionConsulta;
    import Controller.GestionPaciente;
    import Model.Consulta;
    import Model.GestionOrden;
    import Model.Paciente;
    import Model.Receta;
    import javax.swing.JOptionPane;

public class DatosConsulta extends javax.swing.JFrame {
  
    
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(DatosConsulta.class.getName());

    /**
     * Creates new form DatosConsulta
     */
    private GestionConsulta gestorConsulta;
    private GestionPaciente gestorPacientes;
    private GestionOrden gestorOrden;
    private Receta recetaActual;


private int indiceModificar = -1;

public DatosConsulta(GestionConsulta gestor, GestionPaciente gestorPaciente, GestionOrden ordenes, Receta recetaActual) {
    this.gestorConsulta = gestor;
    this.gestorPacientes = gestorPaciente;
    this.gestorOrden = ordenes;
    this.recetaActual = recetaActual;

    initComponents();
    
    
    
    limpiarCampos();
    
    tfMotivo.setColumns(20);
    tfMotivo.setPreferredSize(new java.awt.Dimension(200, tfMotivo.getPreferredSize().height));

    
    tfPrecio.setColumns(10);
    tfPrecio.setPreferredSize(new java.awt.Dimension(120, tfPrecio.getPreferredSize().height));

    cargarPacientes();
}
    
    public void cargarPacientes() {
        jbPaciente.removeAllItems();

        for (int i = 0; i < gestorPacientes.getNumPacientes(); i++) {
            Paciente p = gestorPacientes.getPaciente(i);
            jbPaciente.addItem(p.getNombre() + " " + p.getApellido());
        }
        
        jbPaciente.addActionListener(e -> actualizarArchivos());
    }
    
    
    public void actualizarArchivos() {
        int i = jbPaciente.getSelectedIndex();
        if (i == -1) return;

        Paciente p = gestorPacientes.getPaciente(i);

        jLabel8.setText("A-" + p.getApellido() + ".pdf");  
        jLabel7.setText("S-" + p.getApellido() + ".pdf");
        lExamen.setText("E-" + p.getApellido() + ".pdf");
    
}
    
    
    private void limpiarCampos() {
        tfMotivo.setText("          ");
        tfPrecio.setText("          ");
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        tfMotivo = new javax.swing.JTextField();
        jbPaciente = new javax.swing.JComboBox<>();
        bReceta = new javax.swing.JButton();
        bAceptar = new javax.swing.JButton();
        bCancelar = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();
        tfPrecio = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        bOrden = new javax.swing.JButton();
        lExamen = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel2.setText("Motivo");

        jLabel3.setText("Antecedentes:");

        jLabel4.setText("Signos Vitales:");

        jLabel5.setText("Examen Físico:");

        jLabel6.setText("Plan + Receta:");

        jLabel7.setText("-----");

        jLabel8.setText("-----");

        jLabel9.setText("Paciente");

        tfMotivo.setText("jTextField1");
        tfMotivo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfMotivoActionPerformed(evt);
            }
        });

        jbPaciente.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jbPaciente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbPacienteActionPerformed(evt);
            }
        });

        bReceta.setText("Agregar");
        bReceta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bRecetaActionPerformed(evt);
            }
        });

        bAceptar.setText("Aceptar");
        bAceptar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bAceptarActionPerformed(evt);
            }
        });

        bCancelar.setText("Cancelar");
        bCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bCancelarActionPerformed(evt);
            }
        });

        jLabel10.setText("Precio de Consulta");

        tfPrecio.setText("jTextField1");

        jLabel11.setText("Ordenes");

        bOrden.setText("Agregar");
        bOrden.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bOrdenActionPerformed(evt);
            }
        });

        lExamen.setText("-----");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(jLabel10)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(tfPrecio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(layout.createSequentialGroup()
                                    .addGap(78, 78, 78)
                                    .addComponent(jLabel1)
                                    .addGap(38, 38, 38))
                                .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addComponent(jLabel9)
                            .addComponent(jLabel2))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 254, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(bReceta)
                                .addComponent(jLabel7)
                                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(lExamen))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(tfMotivo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jbPaciente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(1, 1, 1))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(bOrden)))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(bAceptar)
                .addGap(62, 62, 62)
                .addComponent(bCancelar)
                .addGap(114, 114, 114))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(95, 95, 95)
                        .addComponent(jLabel1)
                        .addGap(0, 28, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jLabel9)
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(tfMotivo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel2)))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jbPaciente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(32, 32, 32)))))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addComponent(jLabel8))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jLabel7))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(lExamen))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(bReceta))
                .addGap(8, 8, 8)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(bOrden))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(tfPrecio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bAceptar)
                    .addComponent(bCancelar))
                .addContainerGap(18, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tfMotivoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfMotivoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfMotivoActionPerformed

    private void bAceptarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bAceptarActionPerformed
    int i = jbPaciente.getSelectedIndex();
    if (i == -1) {
        JOptionPane.showMessageDialog(this, "Seleccione un paciente");
        return;
    }

    Paciente p = gestorPacientes.getPaciente(i);

    String motivo = tfMotivo.getText();
    String antecedentes = jLabel8.getText();
    String signos = jLabel7.getText();
    String examen = lExamen.getText();
    String precioTxt = tfPrecio.getText();
    
    Receta receta = recetaActual;           
 
    GestionOrden orden = getGestorOrden();
    
    double precio;
    precio = Double.parseDouble(precioTxt);
    
    Consulta c = new Consulta(
        motivo,
        precio,             
        "Cerrada",       
        p,
        antecedentes,
        signos,
        examen,
        receta,
        orden
    );
    
    gestorConsulta.agregarConsulta(c);
    
    GestorConsultas ventana = new GestorConsultas(gestorConsulta);
    ventana.setVisible(true);
    this.dispose();
    }//GEN-LAST:event_bAceptarActionPerformed

    public void setReceta(Receta receta) {
        this.recetaActual = receta;
    }
    
    public void setOrdenes(GestionOrden ordenes) {
        this.gestorOrden = ordenes;
    }

    public void setGestorOrden(GestionOrden go) {
        this.gestorOrden = go;
    }
    
    public GestionOrden getGestorOrden() {
        return gestorOrden;
    }
    
    private void bRecetaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bRecetaActionPerformed
        GestorReceta ventana = new GestorReceta(this.recetaActual,this);
        ventana.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_bRecetaActionPerformed

    private void bOrdenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bOrdenActionPerformed
        GestorOrden ventana = new GestorOrden(this);
        ventana.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_bOrdenActionPerformed

    private void bCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bCancelarActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_bCancelarActionPerformed

    private void jbPacienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbPacienteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jbPacienteActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        
        GestionConsulta gestorC = new GestionConsulta();
        GestionPaciente gestorP = new GestionPaciente();
        GestionOrden gestorO = new GestionOrden();
        Receta receta = new Receta();
        java.awt.EventQueue.invokeLater(() -> new DatosConsulta(gestorC,gestorP,gestorO,receta).setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bAceptar;
    private javax.swing.JButton bCancelar;
    private javax.swing.JButton bOrden;
    private javax.swing.JButton bReceta;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JComboBox<String> jbPaciente;
    private javax.swing.JLabel lExamen;
    private javax.swing.JTextField tfMotivo;
    private javax.swing.JTextField tfPrecio;
    // End of variables declaration//GEN-END:variables
}
