/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package proyectopoo2025;

/**
 *
 * @author Usuario
 */

import Controller.GestionConsulta;
import Model.GestionOrden;
import Model.Orden;
import proyectopoo2025.DatosOrden;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

public class GestorOrden extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(GestorOrden.class.getName());

    /**
     * Creates new form GestorOrden
     */
   private GestionOrden gestor1;
   private DatosConsulta ventanaConsulta;
    
    public GestorOrden(DatosConsulta ventanaConsulta) {
        initComponents();
        this.ventanaConsulta = ventanaConsulta;
        this.gestor1 = ventanaConsulta.getGestorOrden();
        if (this.gestor1 == null) this.gestor1 = new GestionOrden();
        cargarDatosATabla1();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bAgregar1 = new javax.swing.JButton();
        bEliminar1 = new javax.swing.JButton();
        bModificar1 = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        bGuardar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        bAgregar1.setText("Agregar Orden");
        bAgregar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bAgregar1ActionPerformed(evt);
            }
        });

        bEliminar1.setText("Eliminar Orden");
        bEliminar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bEliminar1ActionPerformed(evt);
            }
        });

        bModificar1.setText("Modificar Orden");
        bModificar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bModificar1ActionPerformed(evt);
            }
        });

        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Tipo de Orden", "Descripción ", "Precio (S/.)", "Estado de Orden"
            }
        ));
        jScrollPane2.setViewportView(jTable2);

        bGuardar.setText("Guardar");
        bGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bGuardarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(185, 185, 185)
                        .addComponent(bAgregar1)
                        .addGap(50, 50, 50)
                        .addComponent(bModificar1)
                        .addGap(43, 43, 43)
                        .addComponent(bEliminar1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(213, 213, 213)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 400, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(238, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(bGuardar)
                .addGap(61, 61, 61))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 324, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(51, 51, 51)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bAgregar1)
                    .addComponent(bModificar1)
                    .addComponent(bEliminar1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(bGuardar)
                .addContainerGap(13, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    
    private void cargarDatosATabla1() {

        if (gestor1 == null) {
            gestor1 = new GestionOrden();
        }

        DefaultTableModel model = (DefaultTableModel) jTable2.getModel();
        model.setRowCount(0); // limpiar

        for (int i = 0; i < gestor1.getCantidadOrdenes(); i++) {

            Orden o = gestor1.getOrdenes(i);

            model.addRow(new Object[]{
                o.getNombre(),
                o.getDescripcion(),
                o.getPrecio(),
                o.getEstado(),
            });
        }
    }
    
    private void bAgregar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bAgregar1ActionPerformed
        // TODO add your handling code here:
        DatosOrden ventana = new DatosOrden(gestor1, ventanaConsulta);
        ventana.setVisible(true);
        this.dispose();
        
    }//GEN-LAST:event_bAgregar1ActionPerformed

    private void bEliminar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bEliminar1ActionPerformed
        // TODO add your handling code here:
        int fila = jTable2.getSelectedRow();

        int confirmar = JOptionPane.showConfirmDialog(null, "¿Desea eliminar esta orden?", "Confirmar",
            JOptionPane.YES_NO_OPTION);

        if (confirmar == JOptionPane.YES_OPTION) {
            gestor1.eliminarOrden(fila);
            cargarDatosATabla1();
        }
    }//GEN-LAST:event_bEliminar1ActionPerformed

    private void bModificar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bModificar1ActionPerformed
        // TODO add your handling code here:
        
        int fila = jTable2.getSelectedRow();

        if (fila == -1) {
            JOptionPane.showMessageDialog(this, "Selecciona una orden primero");
            return;
        }

        Orden o = gestor1.getOrdenes(fila);

         DatosOrden ventana = new DatosOrden(
            gestor1,
            ventanaConsulta            
         );
    
        ventana.setDatos(o, fila);
        ventana.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_bModificar1ActionPerformed

    private void bGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bGuardarActionPerformed

        ventanaConsulta.setGestorOrden(gestor1);
        JOptionPane.showMessageDialog(this, "Órdenes guardadas correctamente");
        ventanaConsulta.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_bGuardarActionPerformed

    /**
     * @param args the command line arguments
     */


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bAgregar1;
    private javax.swing.JButton bEliminar1;
    private javax.swing.JButton bGuardar;
    private javax.swing.JButton bModificar1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable2;
    // End of variables declaration//GEN-END:variables
}
