/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package proyectopoo2025;

import Controller.GestorUsuarios;
import Controller.GestionCitas;
import Controller.GestionConsulta;
import Controller.GestionConsultorios;
import Controller.GestionEmpleados;
import Controller.GestionFactura;
import Controller.GestionPaciente;
import Model.GestionOrden;
import Model.Administrador;
import Model.Cajero;
import Model.Empleado;
import Model.Enfermero;
import Model.Medico;
import Model.Recepcionista;
import Model.Usuario;
import javax.swing.JOptionPane;

/**
 *
 * @author Usuario
 */
public class Login extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(Login.class.getName());
    
    private GestorUsuarios usuarios;

    private GestionEmpleados gestorEmpleados;
    private GestionPaciente gestorPaciente;
    private GestionCitas gestorCitas;
    private GestionConsultorios gestorConsultorios;
    private GestionConsulta gestorConsulta;
    private GestionFactura gestorFactura;
    private GestionOrden gestorOrden;

    

    /**
     * Creates new form Login
     */
    public Login(GestionEmpleados ge, GestionPaciente gp, GestionCitas gc,
             GestionConsultorios gco, GestionConsulta gcon,
             GestionFactura gf, GestionOrden go) {
        initComponents();
        usuarios = new GestorUsuarios();

        this.gestorEmpleados = ge;
        this.gestorPaciente = gp;
        this.gestorCitas = gc;
        this.gestorConsultorios = gco;
        this.gestorConsulta = gcon;
        this.gestorFactura = gf;
        this.gestorOrden = go;

        
        Empleado a1 = new Administrador("70711841", "Diego Alexandro", "Aguayo Arrieta", "Administrador", " ", "962244620", "daguayo@gmail.com");
        usuarios.agregarUsuario("ADM1", "2706", "Administrador", a1);
        
                
        Empleado e1 = new Enfermero("74701841", "Andre Sebastian", "Trigoso Arcaya", "Enfermero", " ", "96478945", "atrigoso@gmail.com");
        usuarios.agregarUsuario("ENF1", "2009", "Enfermero", e1);
        
        Empleado r1 = new Recepcionista("69485623", "Nicolas Mariano", "Uceda Cano", "Recepcionista", " ", "945612304", "nuceda@gmail.com");
        usuarios.agregarUsuario("REC1", "2010", "Recepcionista", r1);
        
        Empleado c1 = new Cajero("74569812", "Aidan Adrian", "Cornejo Canicoba", "Cajero", " ", "93214569", "acornejo@gmail.com");
        usuarios.agregarUsuario("CAJ1", "2011", "Cajero", c1);
        
        Empleado m1 = new Medico("78452319", "Arantxa Angelica", "Ramirez Puccio", "Médico", "Pediatra", "9478622340", "aramirez@gmail.com");
        usuarios.agregarUsuario("MED1", "2004", "Médico", m1);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jpContraseña = new javax.swing.JPasswordField();
        tfUsuario = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();

        jLabel1.setText("Usuario");

        jLabel2.setText("Contraseña");

        jButton1.setText("Aceptar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("Cancelar");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(jLabel1)
                    .addComponent(jButton2))
                .addGap(32, 32, 32)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton1)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jpContraseña)
                        .addComponent(tfUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(158, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(86, 86, 86)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(tfUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(23, 23, 23)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jpContraseña, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(48, 48, 48)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jButton2))
                .addContainerGap(64, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        String user = tfUsuario.getText();
        String pass = jpContraseña.getText();
        
        Usuario u = usuarios.validarUsuario(user, pass);
        
        if (u == null) {
            JOptionPane.showMessageDialog(null, "Usuario o contraseña incorrectos");
            return;
        }
        
        String rol = u.getRoles();
        
        MenudeOpciones menu = new MenudeOpciones(u, gestorEmpleados, gestorCitas, gestorConsultorios, gestorConsulta, gestorFactura, gestorPaciente, gestorOrden);
        menu.setVisible(true);
        
        this.dispose();
            }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        GestionEmpleados ge = new GestionEmpleados();
        GestionPaciente gp = new GestionPaciente();
        GestionCitas gc = new GestionCitas();
        GestionConsultorios gco = new GestionConsultorios();
        GestionConsulta gcon = new GestionConsulta();
        GestionFactura gf = new GestionFactura();
        GestionOrden go = new GestionOrden();
        
        java.awt.EventQueue.invokeLater(() -> new Login(ge, gp, gc, gco, gcon, gf, go).setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPasswordField jpContraseña;
    private javax.swing.JTextField tfUsuario;
    // End of variables declaration//GEN-END:variables
}