/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package proyectopoo2025;

import Controller.GestionCitas;
import Controller.GestionConsulta;
import Controller.GestionConsultorios;
import Controller.GestionEmpleados;
import Controller.GestionFactura;
import Controller.GestionPaciente;
import Model.GestionOrden;
import Model.Receta;
import Model.Usuario;
import Model.Cita;
import Model.Empleado;
import java.awt.Color;


/**
 *
 * @author Usuario
 */
public class MenudeOpciones extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(MenudeOpciones.class.getName());
    private Usuario usuarioLogeado;


    /**
     * Creates new form MenudeOpciones
     */
    
    private GestionEmpleados gestorEmpleados;
    private GestionCitas gestorCitas;
    private GestionConsultorios gestorConsultorios;
    private GestionConsulta gestorConsulta;
    private GestionFactura gestorFactura;
    private GestionPaciente gestorPaciente;
    private GestionOrden gestorOrden;
    
    public MenudeOpciones(Usuario user, 
            GestionEmpleados gestorEmpleados,
            GestionCitas gestorCitas,
            GestionConsultorios gestorConsultorios,
            GestionConsulta gestorConsulta,
            GestionFactura gestorFactura,
            GestionPaciente gestorPaciente,
            GestionOrden gestorOrden) {
        initComponents();
        panelUsuario.setBackground(new java.awt.Color(230, 240, 255));
        tfNombre.setEditable(false);
        tfApellidos.setEditable(false);
        tfDni.setEditable(false);
        tfRol.setEditable(false);
        tfCorreo.setEditable(false);
        tfTelefono.setEditable(false);
        tfEspecialidad.setEditable(false);

        this.usuarioLogeado = user;
        this.gestorEmpleados = gestorEmpleados;
        this.gestorCitas = gestorCitas;
        this.gestorConsultorios = gestorConsultorios;
        this.gestorConsulta = gestorConsulta;
        this.gestorFactura = gestorFactura;
        this.gestorPaciente = gestorPaciente;
        this.gestorOrden = gestorOrden;

        cargarDatosEnPanel();
        jMenuItem1.setText(user.getRoles());  

        if (user != null) {
    switch (user.getRoles()) {

        case "Administrador":
                    miEmpleados.setEnabled(true);
                    miConsultorios.setEnabled(true);
                    miReportes.setEnabled(true);
                    miConsultas.setEnabled(true);
                    miPacientes.setEnabled(true);
                    miFactura.setEnabled(true);
                    miCitas.setEnabled(true);
                    miCheck.setEnabled(true);
                    break;

                case "Recepcionista":
                    miEmpleados.setEnabled(false);
                    miConsultorios.setEnabled(true);
                    miReportes.setEnabled(false);
                    miConsultas.setEnabled(false);
                    miPacientes.setEnabled(true);
                    miFactura.setEnabled(false);
                    miCitas.setEnabled(true);
                    miCheck.setEnabled(true);
                    break;

                case "Medico":
                    miEmpleados.setEnabled(false);
                    miConsultorios.setEnabled(false);
                    miReportes.setEnabled(false);
                    miConsultas.setEnabled(true);
                    miPacientes.setEnabled(true);
                    miFactura.setEnabled(false);
                    miCitas.setEnabled(true);
                    miCheck.setEnabled(false);
                    break;

                case "Enfermero":
                    miEmpleados.setEnabled(false);
                    miConsultorios.setEnabled(false);
                    miReportes.setEnabled(false);
                    miConsultas.setEnabled(true);
                    miPacientes.setEnabled(true);
                    miFactura.setEnabled(false);
                    miCitas.setEnabled(false);
                    miCheck.setEnabled(false);
                    break;

                case "Cajero":
                    miEmpleados.setEnabled(false);
                    miConsultorios.setEnabled(false);
                    miReportes.setEnabled(false);
                    miConsultas.setEnabled(false);
                    miPacientes.setEnabled(false);
                    miFactura.setEnabled(true);
                    miCitas.setEnabled(false);
                    miCheck.setEnabled(false);
                    break;
            }
        }
    }



    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        panelUsuario = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        tfNombre = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        tfApellidos = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        tfDni = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        tfRol = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        tfTelefono = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        tfCorreo = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        tfEspecialidad = new javax.swing.JTextField();
        bCerrar = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        miEmpleados = new javax.swing.JMenuItem();
        miConsultorios = new javax.swing.JMenuItem();
        miReportes = new javax.swing.JMenuItem();
        miConsultas = new javax.swing.JMenuItem();
        miPacientes = new javax.swing.JMenuItem();
        miFactura = new javax.swing.JMenuItem();
        miCitas = new javax.swing.JMenuItem();
        miCheck = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 246, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 385, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        panelUsuario.setForeground(new java.awt.Color(0, 153, 255));

        jLabel1.setText("Nombres");

        tfNombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfNombreActionPerformed(evt);
            }
        });

        jLabel2.setText("Apellidos");

        jLabel3.setText("DNI");

        jLabel4.setText("Rol");

        jLabel5.setText("Telefono");

        jLabel6.setText("Correo");

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        jLabel7.setText("Datos del Usuario");

        jLabel8.setText("Especialidad");

        javax.swing.GroupLayout panelUsuarioLayout = new javax.swing.GroupLayout(panelUsuario);
        panelUsuario.setLayout(panelUsuarioLayout);
        panelUsuarioLayout.setHorizontalGroup(
            panelUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelUsuarioLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel7)
                .addGap(74, 74, 74))
            .addGroup(panelUsuarioLayout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addGroup(panelUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(panelUsuarioLayout.createSequentialGroup()
                        .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(tfCorreo, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(panelUsuarioLayout.createSequentialGroup()
                        .addGroup(panelUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(35, 35, 35)
                        .addGroup(panelUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(tfNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tfApellidos, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tfTelefono, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tfDni, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tfRol, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(panelUsuarioLayout.createSequentialGroup()
                        .addComponent(jLabel8)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(tfEspecialidad, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(42, Short.MAX_VALUE))
        );
        panelUsuarioLayout.setVerticalGroup(
            panelUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelUsuarioLayout.createSequentialGroup()
                .addContainerGap(38, Short.MAX_VALUE)
                .addComponent(jLabel7)
                .addGap(29, 29, 29)
                .addGroup(panelUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(tfNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panelUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(tfApellidos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panelUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(tfDni, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panelUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(tfRol, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panelUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(tfTelefono, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panelUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(tfCorreo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panelUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(tfEspecialidad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(42, 42, 42))
        );

        bCerrar.setText("Cerrar Sesion");
        bCerrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bCerrarActionPerformed(evt);
            }
        });

        jMenu1.setText("Funciones");

        miEmpleados.setText("Empleados");
        miEmpleados.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miEmpleadosActionPerformed(evt);
            }
        });
        jMenu1.add(miEmpleados);

        miConsultorios.setText("Consultorios");
        miConsultorios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miConsultoriosActionPerformed(evt);
            }
        });
        jMenu1.add(miConsultorios);

        miReportes.setText("Reportes");
        miReportes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miReportesActionPerformed(evt);
            }
        });
        jMenu1.add(miReportes);

        miConsultas.setText("Consultas");
        miConsultas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miConsultasActionPerformed(evt);
            }
        });
        jMenu1.add(miConsultas);

        miPacientes.setText("Pacientes");
        miPacientes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miPacientesActionPerformed(evt);
            }
        });
        jMenu1.add(miPacientes);

        miFactura.setText("Facturas");
        miFactura.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miFacturaActionPerformed(evt);
            }
        });
        jMenu1.add(miFactura);

        miCitas.setText("Citas");
        miCitas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miCitasActionPerformed(evt);
            }
        });
        jMenu1.add(miCitas);

        miCheck.setText("Check In");
        miCheck.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miCheckActionPerformed(evt);
            }
        });
        jMenu1.add(miCheck);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Rol");

        jMenuItem1.setText("jMenuItem1");
        jMenuItem1.setEnabled(false);
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem1);

        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(bCerrar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 185, Short.MAX_VALUE)
                .addComponent(panelUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(23, 23, 23))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(bCerrar)
                    .addComponent(panelUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    
    private void cargarDatosEnPanel() {
    if (usuarioLogeado == null) return;

        Empleado emp = usuarioLogeado.getEmpleado();

        tfNombre.setText(emp.getNombres());
        tfApellidos.setText(emp.getApellidos());
        tfDni.setText(emp.getDNI());
        tfRol.setText(emp.getRol());
        tfCorreo.setText(emp.getCorreo());
        tfTelefono.setText(emp.getTelefono());
        if(emp.getRol().equalsIgnoreCase("Médico")){
            tfEspecialidad.setVisible(true); 
            jLabel8.setVisible(true);
            tfEspecialidad.setText(emp.getEspecialidad());
        }
        else {
            tfEspecialidad.setVisible(false);
            jLabel8.setVisible(false);
        }
    }
    
    private void miEmpleadosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miEmpleadosActionPerformed
        // TODO add your handling code here:
        GestorEmpleados ventana = new GestorEmpleados(gestorEmpleados);
        ventana.setVisible(true);
    }//GEN-LAST:event_miEmpleadosActionPerformed

    private void miReportesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miReportesActionPerformed
        Reportes ventana = new Reportes(gestorConsulta, gestorConsultorios, gestorCitas);
        ventana.setVisible(true);
    }//GEN-LAST:event_miReportesActionPerformed

    private void miConsultasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miConsultasActionPerformed
        // TODO add your handling code here:
        DatosConsulta ventana = new DatosConsulta(gestorConsulta, gestorPaciente, gestorOrden, new Receta());
        ventana.setVisible(true);
    }//GEN-LAST:event_miConsultasActionPerformed

    private void miPacientesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miPacientesActionPerformed
        // TODO add your handling code here:
        GestorPacientes ventana = new GestorPacientes(gestorPaciente);
        ventana.setVisible(true);
    }//GEN-LAST:event_miPacientesActionPerformed

    private void miFacturaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miFacturaActionPerformed
        // TODO add your handling code here:
        GestorFactura ventana = new GestorFactura(gestorFactura, gestorOrden, gestorConsulta);
        ventana.setVisible(true);
    }//GEN-LAST:event_miFacturaActionPerformed

    private void miCitasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miCitasActionPerformed
        GestorCitas ventana = new GestorCitas(gestorCitas, gestorPaciente, gestorEmpleados);
        ventana.setVisible(true);
    }//GEN-LAST:event_miCitasActionPerformed

    private void miConsultoriosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miConsultoriosActionPerformed
        GestorConsultorios ventana = new GestorConsultorios(gestorConsultorios);
        ventana.setVisible(true);
    }//GEN-LAST:event_miConsultoriosActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void tfNombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfNombreActionPerformed
            // TODO add your handling code here:
    }//GEN-LAST:event_tfNombreActionPerformed

    private void miCheckActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miCheckActionPerformed
        // TODO add your handling code here:
        Check ventana = new Check(gestorCitas, gestorPaciente);
        ventana.setVisible(true);
    }//GEN-LAST:event_miCheckActionPerformed

    private void bCerrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bCerrarActionPerformed
        // TODO add your handling code here:
        Login ventanaLogin = new Login(
        gestorEmpleados,
        gestorPaciente,
        gestorCitas,
        gestorConsultorios,
        gestorConsulta,
        gestorFactura,
        gestorOrden
    );
    ventanaLogin.setVisible(true);
    this.dispose(); 
    }//GEN-LAST:event_bCerrarActionPerformed

    



    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bCerrar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JMenuItem miCheck;
    private javax.swing.JMenuItem miCitas;
    private javax.swing.JMenuItem miConsultas;
    private javax.swing.JMenuItem miConsultorios;
    private javax.swing.JMenuItem miEmpleados;
    private javax.swing.JMenuItem miFactura;
    private javax.swing.JMenuItem miPacientes;
    private javax.swing.JMenuItem miReportes;
    private javax.swing.JPanel panelUsuario;
    private javax.swing.JTextField tfApellidos;
    private javax.swing.JTextField tfCorreo;
    private javax.swing.JTextField tfDni;
    private javax.swing.JTextField tfEspecialidad;
    private javax.swing.JTextField tfNombre;
    private javax.swing.JTextField tfRol;
    private javax.swing.JTextField tfTelefono;
    // End of variables declaration//GEN-END:variables
}
