/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package proyectopoo2025;

import Controller.GestionEmpleados;
import Controller.GestionPaciente;
import Model.Usuario;

/**
 *
 * @author Usuario
 */
public class MenudeOpciones extends javax.swing.JFrame {
  
    private GestionEmpleados gestor;
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(MenudeOpciones.class.getName());
    

    /**
     * Creates new form MenudeOpciones
     */
    public MenudeOpciones(Usuario user) {
        initComponents();
        gestor = new GestionEmpleados();
        switch (user.getRoles()){
            case "Administrador":
                this.miConsultas.setEnabled(true);
                this.miConsultorios.setEnabled(true);
                this.miEmpleados.setEnabled(true);
                this.miPacientes.setEnabled(true);
                this.miReportes.setEnabled(true);
                break;
            case "Médico":
                this.miConsultas.setEnabled(true);
                this.miConsultorios.setEnabled(true);
                this.miEmpleados.setEnabled(false);
                this.miPacientes.setEnabled(false);
                this.miReportes.setEnabled(false);
                break;
            case "Enfermero":
                this.miConsultas.setEnabled(false);
                this.miConsultorios.setEnabled(true);
                this.miEmpleados.setEnabled(false);
                this.miPacientes.setEnabled(true);
                this.miReportes.setEnabled(false);
                break;
        }
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        miEmpleados = new javax.swing.JMenuItem();
        miConsultorios = new javax.swing.JMenuItem();
        miReportes = new javax.swing.JMenuItem();
        miConsultas = new javax.swing.JMenuItem();
        miPacientes = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();

        jMenu1.setText("File");

        miEmpleados.setText("Empleados");
        miEmpleados.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miEmpleadosActionPerformed(evt);
            }
        });
        jMenu1.add(miEmpleados);

        miConsultorios.setText("Consultorios");
        jMenu1.add(miConsultorios);

        miReportes.setText("Reportes");
        jMenu1.add(miReportes);

        miConsultas.setText("Consultas");
        jMenu1.add(miConsultas);

        miPacientes.setText("Pacientes");
        jMenu1.add(miPacientes);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Edit");
        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 479, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 329, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void miEmpleadosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miEmpleadosActionPerformed

        GestorEmpleados ventana = new GestorEmpleados(gestor);
        ventana.setVisible(true); 
         
    }//GEN-LAST:event_miEmpleadosActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new MenudeOpciones(null).setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem miConsultas;
    private javax.swing.JMenuItem miConsultorios;
    private javax.swing.JMenuItem miEmpleados;
    private javax.swing.JMenuItem miPacientes;
    private javax.swing.JMenuItem miReportes;
    // End of variables declaration//GEN-END:variables
}
