/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package proyectopoo2025;

import Controller.GestionCitas;
import Controller.GestionConsultorios;
import Controller.GestionConsulta;
import Controller.GestionEmpleados;
import Controller.GestionFactura;
import Controller.GestionPaciente;
import Model.GestionOrden;
import Model.Receta;
import Model.Usuario;

/**
 *
 * @author Usuario
 */
public class MenudeOpciones extends javax.swing.JFrame {

    private GestionEmpleados gestorEmpleados;
    private GestionCitas gestorCitas;
    private GestionConsultorios gestorConsultorios;
    private GestionConsulta gestorConsulta;
    private GestionFactura gestorFactura;
    private GestionPaciente gestorPaciente;
    private GestionOrden gestorOrden;
    private javax.swing.JDesktopPane desktopPane;

    private static final java.util.logging.Logger logger = java.util.logging.Logger
            .getLogger(MenudeOpciones.class.getName());

    /**
     * Creates new form MenudeOpciones
     */
    public MenudeOpciones(Usuario user) {
        initComponents();
        // Initialize all managers here to ensure data persistence
        this.gestorEmpleados = new GestionEmpleados();
        this.gestorPaciente = new GestionPaciente();
        this.gestorCitas = new GestionCitas();
        this.gestorConsultorios = new GestionConsultorios();
        this.gestorConsulta = new GestionConsulta();
        //this.gestorConsulta.setDependencias(gestorPaciente, gestorEmpleados);
        this.gestorFactura = new GestionFactura();
        this.gestorOrden = new GestionOrden();

        if (user != null) {
            switch (user.getRoles()) {
                case "Administrador":
                    this.miConsultas.setEnabled(true);
                    this.miConsultorios.setEnabled(true);
                    this.miEmpleados.setEnabled(true);
                    this.miPacientes.setEnabled(true);
                    this.miReportes.setEnabled(true);
                    this.miFactura.setEnabled(true);
                    break;
                case "Médico":
                    this.miConsultas.setEnabled(true);
                    this.miConsultorios.setEnabled(true);
                    this.miEmpleados.setEnabled(false);
                    this.miPacientes.setEnabled(false);
                    this.miReportes.setEnabled(false);
                    this.miFactura.setEnabled(false);
                    break;
                case "Enfermero":
                    this.miConsultas.setEnabled(false);
                    this.miConsultorios.setEnabled(true);
                    this.miEmpleados.setEnabled(false);
                    this.miPacientes.setEnabled(true);
                    this.miReportes.setEnabled(false);
                    this.miFactura.setEnabled(true);
                    break;
            }
        }
    }

    /**
     * Helper method to open internal frames in the desktop pane
     */
    private void openInternalFrame(javax.swing.JInternalFrame frame) {
        // Close any existing frame with the same title
        for (javax.swing.JInternalFrame existingFrame : desktopPane.getAllFrames()) {
            if (existingFrame.getTitle().equals(frame.getTitle())) {
                existingFrame.dispose();
            }
        }

        desktopPane.add(frame);
        frame.setVisible(true);
        try {
            frame.setSelected(true);
        } catch (java.beans.PropertyVetoException e) {
            logger.log(java.util.logging.Level.WARNING, "Could not select frame", e);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated
    // Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        desktopPane = new javax.swing.JDesktopPane();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        miEmpleados = new javax.swing.JMenuItem();
        miConsultorios = new javax.swing.JMenuItem();
        miReportes = new javax.swing.JMenuItem();
        miConsultas = new javax.swing.JMenuItem();
        miPacientes = new javax.swing.JMenuItem();
        miCitas = new javax.swing.JMenuItem();
        miFactura = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Sistema de Gestión de Clínica");
        setPreferredSize(new java.awt.Dimension(1024, 768));

        desktopPane.setBackground(new java.awt.Color(240, 240, 240));

        jMenu1.setText("File");

        miEmpleados.setText("Empleados");
        miEmpleados.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miEmpleadosActionPerformed(evt);
            }
        });
        jMenu1.add(miEmpleados);

        miConsultorios.setText("Consultorios");
        miConsultorios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miConsultoriosActionPerformed(evt);
            }
        });
        jMenu1.add(miConsultorios);

        miReportes.setText("Reportes");
        miReportes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miReportesActionPerformed(evt);
            }
        });
        jMenu1.add(miReportes);

        miConsultas.setText("Consultas");
        miConsultas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miConsultasActionPerformed(evt);
            }
        });
        jMenu1.add(miConsultas);

        miPacientes.setText("Pacientes");
        miPacientes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miPacientesActionPerformed(evt);
            }
        });
        jMenu1.add(miPacientes);

        miCitas.setText("Citas");
        miCitas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miCitasActionPerformed(evt);
            }
        });
        jMenu1.add(miCitas);

        miFactura.setText("Facturas");
        miFactura.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miFacturaActionPerformed(evt);
            }
        });
        jMenu1.add(miFactura);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Edit");
        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(desktopPane, javax.swing.GroupLayout.DEFAULT_SIZE, 1024, Short.MAX_VALUE));
        layout.setVerticalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(desktopPane, javax.swing.GroupLayout.DEFAULT_SIZE, 738, Short.MAX_VALUE));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void miEmpleadosActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_miEmpleadosActionPerformed
        GestorEmpleados ventana = new GestorEmpleados(gestorEmpleados);
        openInternalFrame(ventana);
    }// GEN-LAST:event_miEmpleadosActionPerformed

    private void miConsultoriosActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_miConsultoriosActionPerformed
        GestorConsultorios ventana = new GestorConsultorios(gestorConsultorios);
        openInternalFrame(ventana);
    }// GEN-LAST:event_miConsultoriosActionPerformed

    private void miPacientesActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_miPacientesActionPerformed
        GestorPacientes ventana = new GestorPacientes(gestorPaciente);
        openInternalFrame(ventana);
    }// GEN-LAST:event_miPacientesActionPerformed

    private void miCitasActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_miCitasActionPerformed
        GestorCitas ventana = new GestorCitas(gestorCitas, gestorPaciente, gestorEmpleados);
        openInternalFrame(ventana);
    }// GEN-LAST:event_miCitasActionPerformed

    private void miConsultasActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_miConsultasActionPerformed
        DatosConsulta ventana = new DatosConsulta(gestorConsulta, gestorPaciente, gestorOrden, new Receta());
        openInternalFrame(ventana);
    }// GEN-LAST:event_miConsultasActionPerformed

    private void miReportesActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_miReportesActionPerformed
        Reportes ventana = new Reportes(gestorConsultorios, gestorConsulta, gestorFactura, gestorOrden);
        openInternalFrame(ventana);
    }// GEN-LAST:event_miReportesActionPerformed

    private void miFacturaActionPerformed(java.awt.event.ActionEvent evt) {
        GestorFactura ventana = new GestorFactura(gestorFactura, gestorOrden, gestorConsulta);
        openInternalFrame(ventana);
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        // <editor-fold defaultstate="collapsed" desc=" Look and feel setting code
        // (optional) ">
        /*
         * If Nimbus (introduced in Java SE 6) is not available, stay with the default
         * look and feel.
         * For details see
         * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        // </editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new MenudeOpciones(null).setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem miCitas;
    private javax.swing.JMenuItem miConsultas;
    private javax.swing.JMenuItem miConsultorios;
    private javax.swing.JMenuItem miEmpleados;
    private javax.swing.JMenuItem miPacientes;
    private javax.swing.JMenuItem miReportes;
    private javax.swing.JMenuItem miFactura;
    // End of variables declaration//GEN-END:variables
}
