/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package proyectopoo2025;

import Controller.GestionConsultorios;
import Controller.GestionConsulta;
import Controller.GestionFactura;
import Model.GestionOrden;
import Model.Consultorio;
import Model.Consulta;
import Model.Orden;
import javax.swing.table.DefaultTableModel;
import java.util.HashMap;
import java.util.Map;

/**
 *
 * @author Usuario
 */
public class Reportes extends javax.swing.JInternalFrame {

        private GestionConsultorios gestorConsultorios;
        private GestionConsulta gestorConsulta;
        private GestionFactura gestorFactura;
        private GestionOrden gestorOrden;

        /**
         * Creates new form Reportes
         */
        public Reportes(GestionConsultorios gc, GestionConsulta gcon, GestionFactura gf, GestionOrden go) {
                this.gestorConsultorios = gc;
                this.gestorConsulta = gcon;
                this.gestorFactura = gf;
                this.gestorOrden = go;
                initComponents();
                cargarReporteOcupacion();
                cargarReporteIngresos();
        }

        private void cargarReporteOcupacion() {
                DefaultTableModel model = (DefaultTableModel) tblOcupacion.getModel();
                model.setRowCount(0);

                if (gestorConsultorios != null) {
                        for (int i = 0; i < gestorConsultorios.getNumConsultorios(); i++) {
                                Consultorio c = gestorConsultorios.getConsultorios(i);
                                model.addRow(new Object[] {
                                                c.getCodigo(),
                                                c.getEspecialidad(),
                                                c.getEstado()
                                });
                        }
                }
        }




        private void cargarReporteIngresos() {
                DefaultTableModel model = (DefaultTableModel) tblIngresos.getModel();
                model.setRowCount(0);

                double totalConsultas = 0;
                double totalServicios = 0;

                if (gestorConsulta != null) {
                        for (int i = 0; i < gestorConsulta.getCantidad(); i++) {
                                totalConsultas += gestorConsulta.getConsultas(i).getPrecio();
                        }
                }

                if (gestorOrden != null) {
                        for (int i = 0; i < gestorOrden.getCantidadOrdenes(); i++) {
                                // Assuming Orden has a price, need to check if it was paid or just created?
                                // For now, listing all.
                                totalServicios += gestorOrden.getOrdenes(i).getPrecio();
                        }
                }

                model.addRow(new Object[] { "Consultas Médicas", totalConsultas });
                model.addRow(new Object[] { "Servicios (Lab/Img/Proc)", totalServicios });
                model.addRow(new Object[] { "TOTAL", totalConsultas + totalServicios });
        }

        /**
         * This method is called from within the constructor to initialize the form.
         * WARNING: Do NOT modify this code. The content of this method is always
         * regenerated by the Form Editor.
         */
        @SuppressWarnings("unchecked")
        // <editor-fold defaultstate="collapsed" desc="Generated Code">
        private void initComponents() {

                jTabbedPane1 = new javax.swing.JTabbedPane();
                jPanel1 = new javax.swing.JPanel();
                jScrollPane1 = new javax.swing.JScrollPane();
                tblOcupacion = new javax.swing.JTable();
                jPanel2 = new javax.swing.JPanel();
                jScrollPane2 = new javax.swing.JScrollPane();
                tblProduccion = new javax.swing.JTable();
                jPanel3 = new javax.swing.JPanel();
                jScrollPane3 = new javax.swing.JScrollPane();
                tblIngresos = new javax.swing.JTable();
                jButton1 = new javax.swing.JButton();

                setClosable(true);
                setMaximizable(true);
                setIconifiable(true);
                setResizable(true);
                setTitle("Reportes Administrativos");

                tblOcupacion.setModel(new javax.swing.table.DefaultTableModel(
                                new Object[][] {

                                },
                                new String[] {
                                                "Consultorio", "Especialidad", "Estado"
                                }));
                jScrollPane1.setViewportView(tblOcupacion);

                javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
                jPanel1.setLayout(jPanel1Layout);
                jPanel1Layout.setHorizontalGroup(
                                jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addGroup(jPanel1Layout.createSequentialGroup()
                                                                .addContainerGap()
                                                                .addComponent(jScrollPane1,
                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                588, Short.MAX_VALUE)
                                                                .addContainerGap()));
                jPanel1Layout.setVerticalGroup(
                                jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addGroup(jPanel1Layout.createSequentialGroup()
                                                                .addContainerGap()
                                                                .addComponent(jScrollPane1,
                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                288, Short.MAX_VALUE)
                                                                .addContainerGap()));

                jTabbedPane1.addTab("Ocupación Consultorios", jPanel1);

                tblProduccion.setModel(new javax.swing.table.DefaultTableModel(
                                new Object[][] {

                                },
                                new String[] {
                                                "Médico", "Nro. Consultas", "Total Facturado"
                                }));
                jScrollPane2.setViewportView(tblProduccion);

                javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
                jPanel2.setLayout(jPanel2Layout);
                jPanel2Layout.setHorizontalGroup(
                                jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addGroup(jPanel2Layout.createSequentialGroup()
                                                                .addContainerGap()
                                                                .addComponent(jScrollPane2,
                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                588, Short.MAX_VALUE)
                                                                .addContainerGap()));
                jPanel2Layout.setVerticalGroup(
                                jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addGroup(jPanel2Layout.createSequentialGroup()
                                                                .addContainerGap()
                                                                .addComponent(jScrollPane2,
                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                288, Short.MAX_VALUE)
                                                                .addContainerGap()));

                jTabbedPane1.addTab("Producción por Médico", jPanel2);

                tblIngresos.setModel(new javax.swing.table.DefaultTableModel(
                                new Object[][] {

                                },
                                new String[] {
                                                "Concepto", "Monto Total"
                                }));
                jScrollPane3.setViewportView(tblIngresos);

                javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
                jPanel3.setLayout(jPanel3Layout);
                jPanel3Layout.setHorizontalGroup(
                                jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addGroup(jPanel3Layout.createSequentialGroup()
                                                                .addContainerGap()
                                                                .addComponent(jScrollPane3,
                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                588, Short.MAX_VALUE)
                                                                .addContainerGap()));
                jPanel3Layout.setVerticalGroup(
                                jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addGroup(jPanel3Layout.createSequentialGroup()
                                                                .addContainerGap()
                                                                .addComponent(jScrollPane3,
                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                288, Short.MAX_VALUE)
                                                                .addContainerGap()));

                jTabbedPane1.addTab("Ingresos Totales", jPanel3);

                jButton1.setText("Actualizar");
                jButton1.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                jButton1ActionPerformed(evt);
                        }
                });

                javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
                getContentPane().setLayout(layout);
                layout.setHorizontalGroup(
                                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addGroup(layout.createSequentialGroup()
                                                                .addContainerGap()
                                                                .addGroup(layout.createParallelGroup(
                                                                                javax.swing.GroupLayout.Alignment.LEADING)
                                                                                .addComponent(jTabbedPane1)
                                                                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING,
                                                                                                layout.createSequentialGroup()
                                                                                                                .addGap(0, 0, Short.MAX_VALUE)
                                                                                                                .addComponent(jButton1)))
                                                                .addContainerGap()));
                layout.setVerticalGroup(
                                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addGroup(layout.createSequentialGroup()
                                                                .addContainerGap()
                                                                .addComponent(jTabbedPane1)
                                                                .addPreferredGap(
                                                                                javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                                .addComponent(jButton1)
                                                                .addContainerGap()));

                pack();
        }// </editor-fold>

        private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {
                cargarReporteOcupacion();
                cargarReporteIngresos();
        }

        // Variables declaration - do not modify
        private javax.swing.JButton jButton1;
        private javax.swing.JPanel jPanel1;
        private javax.swing.JPanel jPanel2;
        private javax.swing.JPanel jPanel3;
        private javax.swing.JScrollPane jScrollPane1;
        private javax.swing.JScrollPane jScrollPane2;
        private javax.swing.JScrollPane jScrollPane3;
        private javax.swing.JTabbedPane jTabbedPane1;
        private javax.swing.JTable tblIngresos;
        private javax.swing.JTable tblOcupacion;
        private javax.swing.JTable tblProduccion;
        // End of variables declaration
}
